#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...


# Aliases
j ()     { jobs -l $*; }
env ()   { printenv ; }
dh ()    { dirs -v $* ; }      ## Directory history

preview()    { enscript -p /tmp/$*.ps $*; open /tmp/$*.ps }


# Display CPU usage stats for commands taking more than 10 seconds
REPORTTIME=10

WATCHFMT="%n has %a %l from %m"
LOGCHECK=30
watch=(all)
log

fpath=(~/Projects/depot_tools/zsh-goodies $fpath)
